name: Update Flake Inputs

on:
  schedule:
    # Run once a month at 00:00 on the 1st day of the month
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Update flake inputs
        run: nix flake update

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add flake.lock
          # Only commit if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "chore: Update flake inputs"
            git push
          else
            echo "No changes to commit"
          fi